# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0002_auto_20160514_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
