# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0003_vote_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='election',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phlcitycouncil.Office'),
        ),
    ]
