# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0004_auto_20160514_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('effective_start_year', models.IntegerField()),
                ('effecive_end_year', models.IntegerField()),
                ('departed', models.CharField(max_length=25)),
                ('notes', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phlcitycouncil.Candidate')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phlcitycouncil.Office')),
            ],
        ),
    ]
