# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0006_auto_20160514_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='race',
            field=models.CharField(blank=True, choices=[('Asian', 'Asian'), ('Black', 'Black'), ('Hispanic', 'Hispanic'), ('White', 'White')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('candidate', 'election')]),
        ),
    ]
