# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0007_auto_20160514_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
