# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0008_person_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
