# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0009_auto_20160514_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican')], max_length=12),
        ),
    ]
