# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0011_auto_20160514_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='state',
            new_name='division',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_number',
        ),
        migrations.AddField(
            model_name='district',
            name='ward',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
