# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0012_auto_20160514_2227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set([('ward', 'division')]),
        ),
    ]
