# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0013_auto_20160515_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='ballot_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
