# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0014_auto_20160904_0319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('candidate', 'election', 'ballot_type')]),
        ),
    ]
