# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0015_auto_20160905_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Democrat', 'Democrat'), ('Green', 'Green'), ('Free Dominion Party', 'Free Dominion Party'), ('Independent', 'Independent'), ('Philadelphia Party', 'Philadelphia Party'), ('Republican', 'Republican'), ('Socialist Workers Party', 'Socialist Workers Party')], max_length=35),
        ),
    ]
