# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0016_auto_20160912_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='effecive_end_year',
        ),
        migrations.RemoveField(
            model_name='term',
            name='effective_start_year',
        ),
    ]
