# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0017_auto_20161111_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Primary', 'Primary'), ('Special', 'Special')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('candidate', 'office', 'start_date', 'end_date', 'departed')]),
        ),
    ]
