# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0019_auto_20161128_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.CharField(choices=[('District', 'District'), ('At-Large', 'At-Large')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
