# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0020_office_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='seat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='departed',
            field=models.CharField(choices=[('Incumbent', 'Incumbent'), ('Re-elected', 'Re-elected'), ('Defeated', 'Defeated'), ('Retired', 'Retired'), ('Resigned', 'Resigned'), ('Scandal', 'Scandal'), ('Died', 'Died')], max_length=25),
        ),
    ]
