# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0022_remove_term_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='seat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
