# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0023_term_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('person',)},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('office',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Democrat', 'Democrat'), ('Green', 'Green'), ('Free Dominion Party', 'Free Dominion Party'), ('Independent', 'Independent'), ('Philadelphia Party', 'Philadelphia Party'), ('Republican', 'Republican'), ('Socialist Workers Party', 'Socialist Workers Party'), ('Vote Jesse Brown', 'Vote Jesse Brown'), ('Education', 'Education')], max_length=35),
        ),
        migrations.AlterField(
            model_name='term',
            name='seat',
            field=models.CharField(blank=True, choices=[('DISTRICT COUNCIL - 1ST DISTRICT', 'DISTRICT COUNCIL - 1ST DISTRICT'), ('DISTRICT COUNCIL - 2ND DISTRICT', 'DISTRICT COUNCIL - 2ND DISTRICT'), ('DISTRICT COUNCIL - 3RD DISTRICT', 'DISTRICT COUNCIL - 3RD DISTRICT'), ('DISTRICT COUNCIL - 4TH DISTRICT', 'DISTRICT COUNCIL - 4TH DISTRICT'), ('DISTRICT COUNCIL - 5TH DISTRICT', 'DISTRICT COUNCIL - 5TH DISTRICT'), ('DISTRICT COUNCIL - 6TH DISTRICT', 'DISTRICT COUNCIL - 6TH DISTRICT'), ('DISTRICT COUNCIL - 7TH DISTRICT', 'DISTRICT COUNCIL - 7TH DISTRICT'), ('DISTRICT COUNCIL - 8TH DISTRICT', 'DISTRICT COUNCIL - 8TH DISTRICT'), ('DISTRICT COUNCIL - 9TH DISTRICT', 'DISTRICT COUNCIL - 9TH DISTRICT'), ('DISTRICT COUNCIL - 10TH DISTRICT', 'DISTRICT COUNCIL - 10TH DISTRICT'), ('COUNCIL AT LARGE SEAT 1', 'COUNCIL AT LARGE SEAT 1'), ('COUNCIL AT LARGE SEAT 2', 'COUNCIL AT LARGE SEAT 2'), ('COUNCIL AT LARGE SEAT 3', 'COUNCIL AT LARGE SEAT 3'), ('COUNCIL AT LARGE SEAT 4', 'COUNCIL AT LARGE SEAT 4'), ('COUNCIL AT LARGE SEAT 5', 'COUNCIL AT LARGE SEAT 5'), ('COUNCIL AT LARGE SEAT 6', 'COUNCIL AT LARGE SEAT 6'), ('COUNCIL AT LARGE SEAT 7', 'COUNCIL AT LARGE SEAT 7')], max_length=50, null=True),
        ),
    ]
